#!/bin/bash

tema=${1} 
nev=${2}
tipus=${3}
tar1=""
tar2=""

mkdir -p DB/${tema}

case "${tipus}" in
   "Fa" ) 
      targ1=${nev}Fa.tex
      targ2=${nev}Mo.tex
      ;;
   "Desc" ) 
      targ1=${nev}Desc.tex
      targ2=${nev}Desc.tex
      ;;
   * ) 
      echo "hasznalat: ${0} tema nev [Fa|Desc]"
      exit 1;
      ;;
esac

if [ -f DB/${tema}/${targ1} ];
then
   echo ""${tema}/${nev}${tipus}" exists."
   exit 1
fi
echo "adding problem: "${tema}/${nev}

cd DB/${tema}
touch ${targ1}
touch ${targ2}
cd ../..
echo "done!"
